-- MySQL Script generated by MySQL Workbench
-- Tue May  6 13:42:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Zakaznici`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zakaznici` (
  `idZakaznici` INT NOT NULL,
  `Jmeno` VARCHAR(45) NOT NULL,
  `Přijmeni` VARCHAR(45) NOT NULL,
  `Tel_čislo` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZakaznici`),
  UNIQUE INDEX `idZakaznici_UNIQUE` (`idZakaznici` ASC),
  UNIQUE INDEX `Tel. čislo_UNIQUE` (`Tel_čislo` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sklad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sklad` (
  `idSklad` INT NOT NULL,
  `Počet` INT NOT NULL,
  PRIMARY KEY (`idSklad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kupon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kupon` (
  `idKupon` INT NOT NULL,
  `Čislo_kuponu` VARCHAR(45) NOT NULL,
  `Sleva` INT NOT NULL,
  `Platnost_do` DATE NOT NULL,
  `Byl_použit` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKupon`),
  UNIQUE INDEX `idKupon_UNIQUE` (`idKupon` ASC),
  UNIQUE INDEX `Čislo kuponu_UNIQUE` (`Čislo_kuponu` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Objednavky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Objednavky` (
  `idObjednavky` INT NOT NULL,
  `Zakaznici_idZakaznici` INT NOT NULL,
  `Sklad_idSklad` INT NOT NULL,
  `Datum_objednavky` DATE NOT NULL,
  `Typ_platby` VARCHAR(45) NOT NULL,
  `Kupon_idKupon` INT NULL,
  PRIMARY KEY (`idObjednavky`),
  UNIQUE INDEX `idObjednavky_UNIQUE` (`idObjednavky` ASC),
  INDEX `fk_Objednavky_Zakaznici1_idx` (`Zakaznici_idZakaznici` ASC),
  INDEX `fk_Objednavky_Sklad1_idx` (`Sklad_idSklad` ASC),
  INDEX `fk_Objednavky_Kupon1_idx` (`Kupon_idKupon` ASC),
  CONSTRAINT `fk_Objednavky_Zakaznici1`
    FOREIGN KEY (`Zakaznici_idZakaznici`)
    REFERENCES `mydb`.`Zakaznici` (`idZakaznici`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objednavky_Sklad1`
    FOREIGN KEY (`Sklad_idSklad`)
    REFERENCES `mydb`.`Sklad` (`idSklad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Objednavky_Kupon1`
    FOREIGN KEY (`Kupon_idKupon`)
    REFERENCES `mydb`.`Kupon` (`idKupon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Občerstvení`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Občerstvení` (
  `idObčerstvení` INT NOT NULL,
  `Sklad_idSklad` INT NOT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Cena` INT NOT NULL,
  `Alergeny` VARCHAR(45) NULL,
  PRIMARY KEY (`idObčerstvení`, `Sklad_idSklad`),
  UNIQUE INDEX `idObčerstvení_UNIQUE` (`idObčerstvení` ASC),
  UNIQUE INDEX `Nazev_UNIQUE` (`Nazev` ASC),
  INDEX `fk_Občerstvení_Sklad1_idx` (`Sklad_idSklad` ASC),
  CONSTRAINT `fk_Občerstvení_Sklad1`
    FOREIGN KEY (`Sklad_idSklad`)
    REFERENCES `mydb`.`Sklad` (`idSklad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dezerty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dezerty` (
  `idDezerty` INT NOT NULL,
  `Sklad_idSklad` INT NOT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Cena` INT NOT NULL,
  `Alergeny` VARCHAR(45) NULL,
  PRIMARY KEY (`idDezerty`, `Sklad_idSklad`),
  UNIQUE INDEX `idDeyerty_UNIQUE` (`idDezerty` ASC),
  UNIQUE INDEX `Nazev_UNIQUE` (`Nazev` ASC),
  INDEX `fk_Dezerty_Sklad1_idx` (`Sklad_idSklad` ASC),
  CONSTRAINT `fk_Dezerty_Sklad1`
    FOREIGN KEY (`Sklad_idSklad`)
    REFERENCES `mydb`.`Sklad` (`idSklad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Napoje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Napoje` (
  `idNapoje` INT NOT NULL,
  `Sklad_idSklad` INT NOT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Cena` INT NOT NULL,
  `Alergeny` VARCHAR(45) NULL,
  PRIMARY KEY (`idNapoje`, `Sklad_idSklad`),
  UNIQUE INDEX `idNapoje_UNIQUE` (`idNapoje` ASC),
  UNIQUE INDEX `Nazev_UNIQUE` (`Nazev` ASC),
  INDEX `fk_Napoje_Sklad1_idx` (`Sklad_idSklad` ASC),
  CONSTRAINT `fk_Napoje_Sklad1`
    FOREIGN KEY (`Sklad_idSklad`)
    REFERENCES `mydb`.`Sklad` (`idSklad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
